version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.backend
    volumes:
      - ./data/jsondb/:/app/jsondb:rw
    networks:
      - filiera360_default
    expose:
      - "5000"             # visto solo dagli altri container
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  frontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.frontend
    networks:
      - filiera360_default
    expose:
      - "3001"

  middleware:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.middleware
    ports:
      - "3000:3000"
    networks:
      - filiera360_default
      - fabric_test
    volumes:
      - ./linux_files/fabric-samples/test-network:/test-network:ro
    environment:
      - PEER_ENDPOINT=peer0.org1.example.com:7051

  nginx:
    image: nginx:stable
    ports:
      - "80:80"              # un’unica porta pubblica
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - filiera360_default

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - filiera360_default

  test:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.test
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    networks:
      - filiera360_default
    depends_on:
      - backend
      - mongodb

networks:
  filiera360_default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/16"
          gateway: "172.19.0.1"
  fabric_test:
    external: true

volumes:
  mongo_data:
