version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.backend
    networks:
      - filiera360_default
    restart: always

  frontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - BROWSER=none
    networks:
      - filiera360_default
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro


  middleware:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.middleware
    networks:
      - filiera360_default
      - fabric_test
    volumes:
      - /home/ubuntu/Filiera360/linux_files/fabric-samples/test-network:/test-network:ro
    environment:
    - PEER_ENDPOINT=peer0.org1.example.com:7051
    restart: always

networks:
  filiera360_default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/16"
          gateway: "172.19.0.1"
  fabric_test:
    external: true
