

services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.backend
    volumes:
      - ./jsondb/:/app/jsondb:rw
    networks:
      - filiera360_default
    extra_hosts:
      - "peer0.org1.example.com:172.19.0.6"  # IP del peer
    expose:
      - "5000"             # visto solo dagli altri container

  frontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.frontend
    networks:
      - filiera360_default
    volumes:
    - ./product-tracking/src:/app/src
    ports:
      - "3001:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true

  middleware:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.middleware
    ports:
      - "3000:3000"
    networks:
      - filiera360_default
      - fabric_test
    volumes:
      - ./linux_files/fabric-samples/test-network:/test-network:ro
    environment:
      - PEER_ENDPOINT=peer0.org1.example.com:7051
  mongodb:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile.mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - filiera360_default
  nginx:
    image: nginx:stable
    ports:
      - "80:80"              # un’unica porta pubblica
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - filiera360_default

networks:
  filiera360_default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/16"
          gateway: "172.19.0.1"
  fabric_test:
    external: true
 