FROM node:18-alpine as builder

WORKDIR /build/app
COPY product-tracking .
RUN npm ci
RUN npm run build

FROM nginx:stable as runner
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /build/app/build /www/app/
