FROM python:3.8-slim

WORKDIR /app

COPY app.py /app/app.py
COPY requirements.txt /app/requirements.txt
COPY prompts_variables_storage.py /app/prompts_variables_storage.py
# COPY ./invite_tokens.json /app/
COPY users.json /app/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 5000

# Comando di avvio aggiornato per bind esterno
CMD ["flask", "run", "--host=0.0.0.0"]
