FROM python:3.8-slim

WORKDIR /app
ENV PYTHONUNBUFFERED=1 \
    FLASK_APP=app.py \
    FLASK_ENV=development \
    FLASK_DEBUG=1

COPY app.py requirements.txt prompts_variables_storage.py ./

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 5000
CMD ["flask", "--app", "app.py", "run", "--host=0.0.0.0", "--debug", "--reload"]

 